#!/bin/sh
unset SSH_AUTH_SOCK
ssh -o CheckHostIP=no -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o LogLevel=INFO -o IdentityFile=/home/deploy/.ssh/wordpress-deploy-key -o IdentitiesOnly=yes $*
